# Generated by Django 4.0.5 on 2022-06-24 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True
    auto_now_add = True
    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=300)),
                ('pub_date', models.DateField()),
            ],
        ),
    ]
