# Generated by Django 4.0.5 on 2022-06-25 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_products_delete_product'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
