# Generated by Django 4.0.5 on 2022-06-29 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_contact_rename_sub_category_product_subcategory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='subcategory',
            new_name='sub_category',
        ),
    ]
